using System.ComponentModel;
using System.Text;
using Microsoft.Extensions.Logging;
using Temporalio.Workflows;
using Xians.Lib.Agents.Core;
using Xians.Lib.Agents.Messaging;

namespace Xians.Examples.FileUpload;

/// <summary>
/// Custom Temporal workflow that sends files to the user from deterministic workflow code
/// (as opposed to the message handlers in Program.cs, which run inside an activity).
///
/// Sending a file from workflow code runs as a Temporal activity under the hood, so the request
/// is serialized into workflow history. That leads to the two paths demonstrated below:
/// generated bytes must stay small, while uploads the platform already stores cost nothing.
/// </summary>
[Description("Sends an agent-generated report file - and echoes stored uploads - from workflow code")]
[Workflow("File Upload Agent:File Report Workflow")]
public class FileReportWorkflow
{
    [WorkflowRun]
    public async Task RunAsync(FileReportRequest request)
    {
        Workflow.Logger.LogInformation(
            "FileReportWorkflow started for {ParticipantId} with {StoredFileCount} stored upload(s).",
            request.ParticipantId,
            request.StoredFiles.Count);

        // 1) A file the agent produces here. The bytes travel to the send activity inside a Temporal
        //    payload and end up in workflow history, which is why generated files must stay small
        //    (roughly 1 MB in total). Anything bigger should be produced and sent from an activity.
        var report = Encoding.UTF8.GetBytes(BuildReport(request));
        await XiansContext.Messaging.SendFileAsSupervisorAsync(
            [UploadedFile.FromBytes(report, "workflow-report.txt", "text/plain")],
            text: "Here is a report generated from workflow code.",
            participantId: request.ParticipantId);

        // 2) Files that already live on the platform. They carry a FileId, so they are forwarded by
        //    reference: no bytes in workflow history and no second upload. Size limits do not apply.
        if (request.StoredFiles.Count > 0)
        {
            await XiansContext.Messaging.SendFileAsSupervisorAsync(
                request.StoredFiles,
                text: $"And here are your {request.StoredFiles.Count} upload(s), echoed by reference.",
                participantId: request.ParticipantId);
        }

        Workflow.Logger.LogInformation("FileReportWorkflow completed for {ParticipantId}.", request.ParticipantId);
    }

    private static string BuildReport(FileReportRequest request)
    {
        var lines = new List<string>
        {
            "Report generated inside workflow code",
            $"Created at: {Workflow.UtcNow:O}",
            $"Participant: {request.ParticipantId}",
            $"Note: {request.Note ?? "(none)"}",
            $"Uploads forwarded by reference: {request.StoredFiles.Count}"
        };

        foreach (var file in request.StoredFiles)
        {
            lines.Add($"  - {file.FileName} ({file.ContentType}, {file.FileSize} bytes, fileId={file.FileId})");
        }

        // "\n" rather than Environment.NewLine: workflow code must produce the same bytes on every
        // replay, including on a worker running a different OS.
        return string.Join("\n", lines);
    }
}

/// <summary>
/// Input for <see cref="FileReportWorkflow"/>. Uploaded files are passed as references only
/// (FileId, no bytes) so the workflow argument stays small.
/// </summary>
public class FileReportRequest
{
    public required string ParticipantId { get; set; }

    /// <summary>Optional note echoed into the generated report.</summary>
    public string? Note { get; set; }

    /// <summary>Reference-only files to echo back to the user.</summary>
    public IReadOnlyList<UploadedFile> StoredFiles { get; set; } = [];
}
