using Xians.Examples.FileUpload;
using Xians.Lib.Agents.Core;
using Xians.Lib.Agents.Messaging;
using DotNetEnv;
using Microsoft.Extensions.Logging;
using System.Text;

// -----------------------------------------------------------------------------
// File Upload example
//
// Shows both ways an agent can send files to a user:
//   1. From a message handler - say "receipt", or upload a file. Handlers run inside an
//      activity, so the bytes go straight to the platform over HTTP and the full 10 MB per
//      file limit applies.
//   2. From deterministic workflow code - say "report", or upload a file. The send runs as a
//      Temporal activity, so generated bytes pass through workflow history and must stay small,
//      while already-stored uploads are forwarded by reference for free.
// -----------------------------------------------------------------------------

Env.Load();

var serverUrl = Environment.GetEnvironmentVariable("XIANS_SERVER_URL")
    ?? throw new InvalidOperationException("XIANS_SERVER_URL environment variable is not set");
var xiansAgentCertificate = Environment.GetEnvironmentVariable("XIANS_AGENT_CERTIFICATE")
    ?? throw new InvalidOperationException("XIANS_AGENT_CERTIFICATE environment variable is not set");

var xiansPlatform = await XiansPlatform.InitializeAsync(new()
{
    ServerUrl = serverUrl,
    ApiKey = xiansAgentCertificate,
    ConsoleLogLevel = LogLevel.Debug,
    ServerLogLevel = LogLevel.Warning
});

var xiansAgent = xiansPlatform.Agents.Register(new()
{
    Name = "File Upload Agent",
    IsTemplate = true
});

var conversationalWorkflow = xiansAgent.Workflows.DefineSupervisor();

// Sends files from workflow code. Started on demand by the handlers below, so it is not activable.
xiansAgent.Workflows.DefineCustom<FileReportWorkflow>(new() { Activable = false });

conversationalWorkflow.OnUserChatMessage(async (context) =>
{
    // Typing "receipt" exercises the handler path. This handler runs inside an activity, so the
    // bytes are posted straight to the platform over HTTP: no Temporal payload, full 10 MB limit,
    // and DateTime.UtcNow is fine because there is no determinism constraint here.
    if (context.Message.Text.Contains("receipt", StringComparison.OrdinalIgnoreCase))
    {
        var note = Encoding.UTF8.GetBytes($"Generated in a message handler at {DateTime.UtcNow:O}");
        await context.SendFileAsync(
            content: note,
            fileName: "handler-report.txt",
            contentType: "text/plain",
            text: "Here is a file sent from the handler (non-workflow) path.");
        return;
    }

    // Typing "report" exercises the workflow path: no upload needed, the agent generates the file.
    if (context.Message.Text.Contains("report", StringComparison.OrdinalIgnoreCase))
    {
        await context.ReplyAsync("Generating a report from workflow code, one moment…");

        await XiansContext.Workflows.StartAsync<FileReportWorkflow>(
            args:
            [
                new FileReportRequest
                {
                    ParticipantId = context.Message.ParticipantId,
                    Note = context.Message.Text
                }
            ],
            // Handlers run in an activity, not workflow code, so Guid.NewGuid() is fine here.
            uniqueKey: Guid.NewGuid().ToString());
        return;
    }

    await context.ReplyAsync(
        "Try one of these:\n"
        + "  • \"receipt\" — I generate a file from a message handler (non-workflow path)\n"
        + "  • \"report\" — I generate a file from workflow code (Temporal activity path)\n"
        + "  • send a file with type=\"File\" — I save it, reply with a receipt, then echo it back "
        + "from workflow code by reference");
});

conversationalWorkflow.OnFileUpload(async (context) =>
{
    var files = context.Message.Files;

    if (files.Count == 0)
    {
        await context.ReplyAsync("No file data received.");
        return;
    }

    var saveDirectory = Path.Combine(Path.GetTempPath(), "xians-file-uploads");
    Directory.CreateDirectory(saveDirectory);

    var summaries = new List<string>();
    foreach (var file in files)
    {
        if (!file.TryGetBytes(out var fileBytes))
        {
            await context.ReplyAsync(
                $"Invalid file format for '{file.FileName ?? "uploaded-file"}'. Please ensure the file is base64 encoded.");
            return;
        }

        var fileName = Path.GetFileName(file.FileName ?? $"uploaded-file-{Guid.NewGuid():N}");
        var savePath = Path.Combine(saveDirectory, fileName);
        await File.WriteAllBytesAsync(savePath, fileBytes!);

        summaries.Add(
            $"{fileName} ({fileBytes!.Length} bytes" +
            $"{(file.ContentType != null ? $", {file.ContentType}" : "")}) saved to {savePath}");
    }

    // Handler path: this runs in an activity, so the receipt bytes are posted directly over HTTP.
    var receipt = Encoding.UTF8.GetBytes(string.Join(Environment.NewLine, summaries));
    await context.ReplyAsync(
        $"Received {files.Count} file(s) with message '{context.Message.Text}' successfully! {string.Join(", ", summaries)}",
        UploadedFile.FromBytes(receipt, "upload-receipt.txt", "text/plain"));

    // Workflow path: hand the uploads to a workflow as references only (FileId, no bytes) so the
    // workflow argument and history stay small. The workflow echoes them back from workflow code.
    var storedFiles = files
        .Where(file => !string.IsNullOrEmpty(file.FileId))
        .Select(file => new UploadedFile(null, file.FileName, file.ContentType, file.FileSize, file.FileId))
        .ToList();

    await XiansContext.Workflows.StartAsync<FileReportWorkflow>(
        args:
        [
            new FileReportRequest
            {
                ParticipantId = context.Message.ParticipantId,
                Note = context.Message.Text,
                StoredFiles = storedFiles
            }
        ],
        uniqueKey: Guid.NewGuid().ToString());
});

await xiansAgent.RunAllAsync();
